version: "3"

services:
  complaints:
    container_name: complaints
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        - BASE_PATH=/complaints-public-app   #base URL to your app, default=/
    env_file:
      - .env.dev
    restart: always
    ports:
      - 3000:3000
    
